---
# role: ansible-role-updates
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: updates-amazon
    image: "jam82/molecule-amazonlinux:latest"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-centos7
    image: "jam82/molecule-centos:7"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-centos8
    image: "jam82/molecule-centos:8"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-debian9
    image: "jam82/molecule-debian:9"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-debian10
    image: "jam82/molecule-debian:10"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-debian
    image: "jam82/molecule-debian:latest"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-fedora
    image: "jam82/molecule-fedora:latest"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-oracle7
    image: "jam82/molecule-oraclelinux:7"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-oracle8
    image: "jam82/molecule-oraclelinux:8"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-oracle
    image: "jam82/molecule-oraclelinux:latest"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-ubuntu1604
    image: "jam82/molecule-ubuntu:16.04"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-ubuntu1804
    image: "jam82/molecule-ubuntu:18.04"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: updates-ubuntu
    image: "jam82/molecule-ubuntu:latest"
    command: ${MOLECULE_DOCKER_CMD:-""}
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: True
    sudo: True
