---
# role: ansible-role-updates
# file: tasks/tasks.yml

- name: "Set pkg_mgr dependent variables"
  include_vars: '{{ ansible_pkg_mgr }}.yml'

- name: "Set distribution dependent variables"
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: "Install packages for ansible-role-updates"
  package:
    name: "{{ updates_packages }}"
    state: present

- name: "Configure automatic updates"
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: '644'
    validate: "{{ updates_validate }}"
  loop: "{{ updates_templates }}"
  notify: Enable automatic updates
